### ISSUE TITLE
Consultas necesarias para visualización de resultados

### ISSUE THREAD

**Issue by dierodfer** [EGC-G2-Trabajo-1718/recuento-de-votos#11]
**Título**: Consultas necesarias para visualización de resultados
**Prioridad**: alto
**Estado**: pendiente
**Descripción:** 
Se necesita satisfacer la llamadas a sus respectivas APIs, se generará un json con los datos requeridos:

* Para una encuesta finalizada:

1. - [ ] Lista de edades de todos los participantes de una votación finalizada X
2. - [ ] Lista de ciudades con el número de participantes de dichas ciudades de una votación X
3. - [ ] Lista de provincias con el número de participantes de dichas provincias de una votación X
3. - [ ] Lista de países con el número de participantes de dichos países de una votación X
5. - [ ] Lista de horas de todos los votos de una votación X

**Subsistemas involucrados:**
* @EGC-G2-Trabajo-1718/recuento 
* @EGC-G2-Trabajo-1718/visualizacion_resultados 

**Etiquetas:** help wanted

**Comment by dierodfer** [comment]
**Estructura de datos propuesta:**

_Lista de edades de todos los participantes de una encuesta finalizada X_
El tipo .json que solicitamos para realizar una gráfica de edades es el siguiente:
{
"data": [
{"edad": 79},
{"edad": 36},
{"edad": 75}
}
Entiéndase, por cada voto, la edad del votante.

_Lista de ciudad,provincia,país con el número de participantes de dicha ciudad,provincia,país una encuesta X_
El tipo .json que solicitamos para crear una gráfica basada en las ciudades es el siguiente:
{
"data": [
{"huelva": 416},
{"sevilla": 49 },
{"cadiz": 100},
{"cordoba": 211},
{"jaen": 10},
{"almeria": 198}
]
}
Entiéndase, por cada ciudad a la que pertenezca cada votante, el numero total de votos.

_Lista de horas de todos los votos de una votación X_
El tipo .json que solicitamos para crear una gráfica basada en las ciudades es el siguiente:
"horas":[
{"data":[
  {"momento": "2017-12-01 11:52:15 "},
  {"momento": "2017-12-01 09:25:25 "},
  {"momento": "2017-12-01 02:50:07 "},
]}]
Entiéndase, por cada momento a la hora exacta que votó un votante.

**Comment by jucansu** [comment]
Buenas, en primer lugar perdón por la tardanza.
Hemos actualizado en nuestra wiki los parametros que devuelve el json de nuestra api, principalmente lo que devuelve es lo mismo que en las anteriores llamadas pero en vez de la pregunta y las respuestas en sí (como cadena de texto)  lo que devolvemos son id_pregunta e id_respuesta (como integer) ya que almacenamiento tan solo nos facilita los id de dichos parametros en su json.
En la wiki teneís toda la información.
