### ISSUE TITLE
Adaptación del modelo de datos al de almacenamiento

### ISSUE THREAD

**Issue by jucansu** [EGC-G2-Trabajo-1718/recuento-de-votos#13]
Prioridad: Alta.

Adaptación de modelos de datos en conformidad con el modelo de almacenamiento, para que los parámetros de entrada de nuestra api se correspondan con los datos recibidos por el subsistema de Almacenamiento.

**Comment by ajba** [comment]
Se cierra el issue con el siguiente commit: c6d21501c4fe1130d939b9b2bc372a26a5c5c159
