### ISSUE TITLE
Estudiar y definir estructura de ramas GITHUB

### ISSUE THREAD

**Issue by jucansu** [EGC-G2-Trabajo-1718/recuento-de-votos#3]
Prioridad: Urgente.

Se ha de estudiar la forma en la que vamos a dividir nuestro proyecto, en cuantas ramas y con que funcionalidad. En los próximos días se estudiaran las diferentes opciones y se llevará a cabo la mas eficaz para el trabajo del grupo.
Sugerencia: tipo BRANCH.

**Comment by AlfonsoSoldado** [comment]
Ya se ha definido toda la estructura de las ramas y se ha creado una rama por usuario, donde cada uno podrá tocar el código que se encuentra en su propia rama. Todo esto se irá subiendo a la rama master cuando se acabe alguna funcionalidad. Finalmente se creará una última rama _deployment_ donde se subirá todo el proyecto cuando esté acabado. Cierro el issue.
