### ISSUE TITLE
Programar recibir API

### ISSUE THREAD

**Issue by jucansu** [EGC-G2-Trabajo-1718/recuento-de-votos#6]
Prioridad: Alta

Se ha de implementar los métodos que se encarguen de procesar los JSON que recibiremos de las demás API. 
Principalmente necesitamos recibir una lista de todos los votos almacenados por el subsistema de Almacenamiento de votos.

**Comment by ajba** [comment]
Se cierra el issue con el siguiente commit: c6d21501c4fe1130d939b9b2bc372a26a5c5c159
