### ISSUE TITLE
Wiki desactualizada

### ISSUE THREAD

**Issue by javsanpar** [EGC-G2-Trabajo-1718/recuento-de-votos#8]
Varios apartados de la Wiki de EGC se encuentra desactualizados, como "Tecnologías elegidas" y "Gestión del código"

Tampoco me deja asignar etiquetas a los Issues.

**Comment by danirguez** [comment]
Los apartados de tecnologías elegidas y gestión del código del espacio del grupo de la wiki han sido actualizados correctamente conforme a las tecnologías utilizadas. Cierro el issue.
